version: 2

models:
  - name: dim_carmake
    description: >
      Dimensión de marcas de vehículos generada a partir de los datos agregados
      de ventas mensuales. Contiene una fila por cada marca de vehículo (car_make)
      con una clave sustituta determinista basada en un Hash MD5.

    columns:
      - name: ID_CARMAKE
        description: >
          Clave sustituta (Surrogate Key) de la marca, generada mediante el Hash 
          del campo car_make para asegurar consistencia e inmutabilidad.
        tests:
          - unique
          - not_null

      - name: car_make
        description: >
          Nombre de la marca del vehículo (por ejemplo: Toyota, Ford, Nissan).
        tests:
          - not_null

  - name: dim_salesperson
    description: >
      Dimensión de vendedores generada a partir de los datos agregados de ventas
      mensuales. Contiene una fila por cada vendedor con una clave sustituta determinista.

    columns:
      - name: ID_SALESPERSON
        description: >
          Clave sustituta (Surrogate Key) del vendedor, generada mediante el Hash 
          del nombre del salesperson para asegurar consistencia e inmutabilidad.
        tests:
          - unique
          - not_null

      - name: salesperson
        description: >
          Nombre del vendedor responsable de la venta.
        tests:
          - not_null

  - name: fact_montly_sales
    description: >
      Tabla de hechos que contiene las métricas agregadas de ventas mensuales.
      Se conecta con las dimensiones mediante las claves sustitutas Hash correspondientes.

    columns:
      - name: ddate
        description: Fecha asociada a la venta o al período agregado.
        tests:
          - not_null

      - name: ID_SALESPERSON
        description: HASH ID del vendedor para relacionar con dim_salesperson.
        tests:
          - not_null
          #- relationships: { to: ref('dim_salesperson'), field: ID_SALESPERSON }

      - name: ID_CARMAKE
        description: HASH ID de la marca para relacionar con dim_carmake.
        tests:
          - not_null
          #- relationships: { to: ref('dim_carmake'), field: ID_CARMAKE }

      - name: totalsales
        description: Monto total de ventas en el período.

      - name: totalcom
        description: Total de comisión generada en el período.